#!/usr/bin/env bash
# Usage: git fixup [BRANCH]
# Allows the selection of a commit to be used with `rebase --autosquash`.
# v1.1.0

# We actually want globbing and word splitting for the FZF_OPTIONS variable.
# shellcheck disable=SC2086

# TODO: completion for branches.

# Quit when there's an error.
set -e

default_branch='origin/master'
default_fzf_options='--height 40% --reverse'

# Use the first argument as branch or fallback to the configuration or to the
# default value.
if [[ -n "$1" ]]; then
  BRANCH="$1"
else
  BRANCH=$(git config --get 'fixup.branch' || echo $default_branch)
fi

FZF_OPTIONS=$(git config --get 'fixup.fzfOptions' || echo $default_fzf_options)

# Pick from those commits.
# TODO: Make the picker configurable.
sha1=$(git log "$BRANCH"..HEAD --pretty=format:'%H' | fzf $FZF_OPTIONS --preview='git show {}')

# Commit!
git commit --fixup="$sha1"
